### ISSUE TITLE
Скласти інтро

### ISSUE THREAD

**Issue by aramatk** [aramatk/homepage#4]
Скласти інтро (вступ), де в 2-4 реченнях описати, що замовник робить, що подобається робити, що хочеться робити краще, що важливо робити, тощо.

**Comment by tamara-kyr** [comment]
I am an experienced computer engineer. I like challenges and always eager to find a better solution, that greatly benefits the business and enhances the user experience. I have a passion for learning new technologies and improving myself.

**Comment by aramatk** [comment]
Nice brief.
