### ISSUE TITLE
Скласти блок контактної інформації

### ISSUE THREAD

**Issue by aramatk** [aramatk/homepage#5]
Посилання на соцмережі (Facebook чи Instagram, тощо), номер телефону чи адреса електронної скриньки, тощо. Може не всі лінки в світі, а тільки ті, що дійсно доречні.

**Comment by tamara-kyr** [comment]
https://www.linkedin.com/in/tamara-kyrychenko-067b9b41/
https://www.facebook.com/tamara.kyrychenko
email tamara.kyrychenko@gmail.com

**Comment by aramatk** [comment]
https://github.com/aramatk

**Comment by aramatk** [comment]
Good job!
