### ISSUE TITLE
Скласти таймлайн

### ISSUE THREAD

**Issue by aramatk** [aramatk/homepage#6]
Скласти список всіх (важливих) життєвих подій, визначних дат, досягнень, періодів, що дали приємний і неприємний досвід, тощо. В цьому конкретному випадку довгих списків не буває, натомість бувають погано згорнуті, тому пакуємо сюди все підряд, а про "лишні" події можна буде промовчати пізніше. Список повинен бути систематизованим і посортованим в такий спосіб, щоб читач швидко зрозумів "паттерн" і міг легко орієнтуватись в просторі і часі цього резюме.

**Comment by tamara-kyr** [comment]
Oct 2012 – Present
Java Full Stack Developer
Sintez Technologies
As part of the scrum team develop and maintain a single-page rich web application for hospital management:
• Developing logical components on the front-end.
• Developing back-end business logic.
• Creating complex reports using Jasper report technology.
• Writing unit tests.

Mar 2011 – Oct 2012
Flex Developer
Sintez Technologies
Woked on developing front-end components.

2005 – 2011
Admiral Makarov National University of Shipbuilding
Master's Degree
Computer Systems Analyst
GPA: 5.0
