### ISSUE TITLE
Скласти додаткові інформаційні блоки

### ISSUE THREAD

**Issue by aramatk** [aramatk/homepage#7]
Можна зробити резюме менш формальним, додавши додаткові блоки, які містять корисну інформацію, але подають її в "розважальній" формі. Наприклад, що подобається і не подобається, сильні і слабкі сторони, перелік навиків чи хобі, інфографіка або ж інтерактивні модулі, тощо. Варто написати контент такого блоку раніше, ніж починати верстку, бо його розміри впливатимуть на розміщення елементів на сторінці.

**Comment by tamara-kyr** [comment]
Languages
Russian (Native or Bilingual)
Ukrainian (Native or Bilingual)
English (Professional Working)
Certifications
Web Application Architectures 2014
English Certification SoftServe IT Academy 2020
Web UI Certification SoftServe IT Academy 2020
Java Certification SoftServe IT Academy
Interest 
Running,
Travelling,
Theatre,
Reading.

**Comment by tamara-kyr** [comment]
PROGRAMMING LANGUAGES & TOOLS
Java, GWT, MVP4G, Spring, Spring Data JPA, QueryDSL, OOP, JavaScript, React
General skills: Communication, Problem Solving,  Teamwork, Attention to details.
